# Generated by Django 3.2.15 on 2023-10-29 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_corp', models.IntegerField(blank=True, null=True)),
                ('count_active_corp', models.IntegerField(blank=True, null=True)),
                ('ships_destroyer', models.IntegerField(blank=True, null=True)),
                ('ships_lost', models.IntegerField(blank=True, null=True)),
                ('point_lost', models.IntegerField(blank=True, null=True)),
                ('point_destroyer', models.IntegerField(blank=True, null=True)),
                ('isk_lost', models.CharField(blank=True, max_length=255, null=True)),
                ('isk_destroyer', models.CharField(blank=True, max_length=255, null=True)),
                ('count_active_chars', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('alli_id', models.IntegerField(blank=True, null=True)),
                ('date_founded_alli', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('killmailID', models.CharField(blank=True, max_length=255, null=True)),
                ('locationID', models.CharField(blank=True, max_length=20, null=True)),
                ('hash_kill', models.CharField(blank=True, max_length=255, null=True)),
                ('fittedValue', models.CharField(blank=True, max_length=255, null=True)),
                ('droppedValue', models.CharField(blank=True, max_length=255, null=True)),
                ('destroyedValue', models.CharField(blank=True, max_length=255, null=True)),
                ('totalValue', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.CharField(blank=True, max_length=255, null=True)),
                ('npc', models.BooleanField(default=False)),
                ('solo', models.BooleanField(default=False)),
                ('awox', models.BooleanField(default=False)),
                ('id_alli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kill.alliancestatic')),
            ],
        ),
        migrations.CreateModel(
            name='KillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_kills', models.IntegerField(blank=True, default=0, null=True)),
                ('ship_loss', models.IntegerField(blank=True, default=0, null=True)),
                ('pvp', models.BooleanField(default=True, verbose_name='шип игрока')),
                ('id_alli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kill.alliancestatic')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.CharField(blank=True, max_length=15, null=True)),
                ('char_name', models.CharField(blank=True, max_length=255, null=True)),
                ('char_kills', models.IntegerField(blank=True, null=True)),
                ('id_alli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kill.alliancestatic')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_id', models.CharField(blank=True, max_length=15, null=True)),
                ('corp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('corp_kills', models.IntegerField(blank=True, null=True)),
                ('id_alli', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kill.alliancestatic')),
            ],
        ),
    ]
