# Generated by Django 3.2.15 on 2023-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kills',
            name='json_kill',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
