# Generated by Django 3.2.15 on 2023-10-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kill', '0002_kills_json_kill'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillFromCCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idkill', models.CharField(blank=True, max_length=255, null=True)),
                ('date_kill', models.DateTimeField(blank=True, null=True)),
                ('json_file', models.JSONField(blank=True, null=True)),
                ('solar_system', models.CharField(blank=True, max_length=255, null=True)),
                ('hash_kill', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_final', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_final_personage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_final_personage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_final_personage_corp', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_final_personage_all', models.CharField(blank=True, max_length=255, null=True)),
                ('attack_final_personage_ship', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_personage_id', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_personage_name', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_personage_corp', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_personage_all', models.CharField(blank=True, max_length=255, null=True)),
                ('victim_personage_ship', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
