# Generated by Django 3.2.15 on 2023-11-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kill', '0003_get_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_attac',
            name='faction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
