# Generated by Django 3.2.15 on 2023-10-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kill', '0003_killfromccp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killfromccp',
            name='date_kill',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
