# Generated by Django 3.2.15 on 2023-11-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kill', '0004_alter_killfromccp_date_kill'),
    ]

    operations = [
        migrations.AddField(
            model_name='killfromccp',
            name='attack_final_personage_all_icon',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='attack_final_personage_all_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='attack_final_personage_corp_icon',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='attack_final_personage_corp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='victim_personage_all_icon',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='victim_personage_all_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='victim_personage_corp_icon',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='victim_personage_corp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='victim_personage_ship_icon',
            field=models.URLField(blank=True, null=True, verbose_name=''),
        ),
    ]
