# Generated by Django 3.2.15 on 2023-11-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kill', '0005_auto_20231102_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='killfromccp',
            name='solar_system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='killfromccp',
            name='solar_system_ss',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
